Don't fsdp_wrap transformer encoder & decoder
Summary:
Per anj-s 's suggestion - this seems to fix the
```
      assert len(self.flat_params) == 1, "Incorrect access to flat_param"
  AssertionError: Incorrect access to flat_param
```
error when training transformer models w/ large number of params

~~(not sure why the number of params affect fairscale FSDP wrapping???)~~ Did this maybe only manifest when the encoder/decoder individually had > 1e8 params due to the default of `min_params_to_wrap`?

Looking at D26771144 (https://github.com/pytorch/fairseq/commit/656d7e5779a9ec4ccf0ad45d86a4ce589c597588) & https://github.com/fairinternal/fairseq-py/pull/1667 where this code was added - it's unclear why wrapping was specifically necessary when share_all_embeddings=False? Is it OK to just delete this code?

(And did the gshard model avoid this issue b/c it used share_all_embeddings=True?)

Reviewed By: huihuifan

Differential Revision: D35084649

fbshipit-source-id: ad5b394c9920e3bea2767a0771f6de36aecb3687